package com.cts.outreach.log.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="log")
public class LogEntity {
	
	private String logid;
	private String eventname;
	private String username;
	private String action;
	private String timestamp;
	
	@DynamoDBHashKey(attributeName="logid")
	@DynamoDBAutoGeneratedKey
	public String getLogid() {
		return logid;
	}
	
	public String getEventname() {
		return eventname;
	}
	@DynamoDBAttribute
	public String getUsername() {
		return username;
	}
	@DynamoDBAttribute
	public String getAction() {
		return action;
	}
	@DynamoDBRangeKey(attributeName="timestamp")
	public String getTimestamp() {
		return timestamp;
	}
	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}
	public LogEntity(String logid, String eventname, String username, String action, String timestamp) {
		super();
		this.logid = logid;
		this.eventname = eventname;
		this.username = username;
		this.action = action;
		this.timestamp = timestamp;
	}
	public LogEntity() {
		super();
		// TODO Auto-generated constructor stub
	}
	
}
